
const DUMMY_LESSONS = [
    {
        id: "l1",
        language: "EN",
        level: "B2",
        title: "Procrastination",
        author: '',
        grammaticalPoint:'',
        imageURL: "https://picsum.photos/id/11/300/300",
        text: `#Ever despaired at your endless capacity for procrastination? Find yourself completing even the smallest task at the very last minute? Are you procrastinating right now by reading this article? Time to stop beating yourself up: according to a new study, as the BBC reports, your procrastination might be the result of the structure of your brain. A study published in Psychological Science observed two areas of the brain that control our propensity to put things off. So let's get deeper into the science: why do people procrastinate? The study pins the likelihood of procrastination on two parts of the brain: the amygdala — "an almond-shaped structure in the temporal (side) lobe which processes our emotions and controls our motivation " — and the dorsal anterior cingulate cortex (or the DACC), which "uses information from the amygdala and decides what action the body will take." The DACC is responsible for "blocking out competing emotions and distractions" — in other words, it's the anti-procrastination part of the brain. After scanning the brains of 264 people, as well as using a survey to measure their proactivity, researchers found that procrastinators tended to have a larger amygdala, as well as a weaker connection between the amygdala and the DACC. Study author Erhan Genç explained, "Individuals with a larger amygdala may be more anxious about the negative consequences of an action — they tend to hesitate and put off things." And a poorer connection between the amygdala and the DACC results in individuals being "less able to filter out interfering emotions and distractions." See? You really can't be blamed for watching eleven consecutive makeup tutorials when you've got a deadline in 45 minutes. It's all down to that darn amygdala!
        So procrastination is linked to your brain #structure — does that mean you can't escape it? Not according to the study authors: while procrastination might have physical roots in the brain, that doesn't mean you're doomed by your biology. Lead author Dr Caroline Schlüter said, "The brain is very responsive and can change throughout the lifespan." And Dr Tim Pychyl, a procrastination expert from Carleton University, told the BBC, "Research has already shown that mindfulness meditation is related to amygdala shrinkage, expansion of the pre-frontal cortex and a weakening of the connection between these two areas." In short? Your brain can change, and so can your unhelpful habits.
        The study authors aren't the only ones to suggest that procrastination isn't just a failure of self control or time management. The Atlantic observed that the habit "might have less to do with time than emotion." The basic emotional process behind procrastination? "We delay action because we feel like we're in the wrong mood to complete a task," the Atlantic noted; plus, "we assume that our mood will change in the near future."
        So what can you do to change your ways? Productivity expert Moyra Scott shared some tips with the BBC, recommending that chronic procrastinators break tasks into smaller, more manageable actions, use a timer to schedule short periods of focus, and minimise external interruptions like notifications from your phone.
        `,
    },
    {
        id: "l2",
        language: "EN",
        level: "B1",
        title: "Unususal jobs",
        author: '',
        grammaticalPoint:'',
        imageURL: "https://picsum.photos/id/12/300/300",
        text: "There is no text",
    },
    {
        id: "l3",
        language: "EN",
        level: "B1",
        title: "Unususal Models",
        author: '',
        grammaticalPoint:'',
        imageURL: "https://picsum.photos/id/200/300/300",
        text: "Being a model isn’t as easy as you think. Getting into the fashion industry needs a lot of struggle and it’s even more difficult when you have no connections. The fashion industry has always been a place for beautiful people, but over the past few years it has become beautifully unique. When we hear the word ‘models’ we always picture good looking men and women in our head, but these unusual models will change the way you think. Here we are going to list the top unusual models in the world who are revolutionizing the fashion industry. You’ve probably heard that beauty lies in the eye of the beholder, and for these unusual models, this phrase has never been so true.",
    },
    {
        id: "l4",
        language: "EN",
        level: "C1",
        title: "A Hero of Our Time",
        author: 'Lermontov',
        grammaticalPoint:'',
        imageURL: "https://picsum.photos/id/201/200/300",
        text: `“Yes, such has been my lot since childhood. Everyone read signs of non-existent evil traits in my features. But since they were expected to be there, they did make their appearance. Because I was reserved, they said I was sly, so I grew reticent. I was keenly aware of good and evil, but instead of being indulged I was insulted and so I became spiteful. I was sulky while other children were merry and talkative, but though I felt superior to them I was considered inferior. So I grew envious. I was ready to love the whole world, but no one understood me, and I learned to hate. My cheerless youth passed in conflict with myself and society, and fearing ridicule I buried my finest feelings deep in my heart, and there they died. I spoke the truth, but nobody believed me, so I began to practice duplicity. Having come to know society and its mainsprings, I became versed in the art of living and saw how others were happy without that proficiency, enjoying for free the favors I had so painfully striven for. It was then that despair was born in my heart--not the despair that is cured with a pistol, but a cold, impotent desperation, concealed under a polite exterior and a good-natured smile. I became a moral cripple; I had lost one half of my soul, for it had shriveled, dried up and died, and I had cut it off and cast it away, while the other half stirred and lived, adapted to serve every comer. No one noticed this, because no one suspected there had been another half. Now, however, you have awakened memories of it in me, and what I have just done is to read its epitaph to you. Many regard all epitaphs as ridiculous, but I do not, particularly when I remember what rests beneath them.”
        ― Mikhail Lermontov, A Hero of Our Time'`,
        difficultWords:['Everyone', 'evil']
    },
    {
        id: "l5",
        language: "EN",
        level: "B1",
        title: "Sth else",
        author: '',
        grammaticalPoint:'',
        imageURL: "https://picsum.photos/id/25/300/300",
        text: "There is no text",
    },
    {
        id: "l6",
        language: "EN",
        level: "B1",
        title: "Sth else",
        author: '',
        grammaticalPoint:'',
        imageURL: "https://picsum.photos/id/26/300/300",
        text: "There is no text",
    },
    {
        id: "l7",
        language: "EN",
        level: "B1",
        title: "Sth else",
        author: '',
        grammaticalPoint:'',
        imageURL: "https://picsum.photos/id/27/300/300",
        text: "There is no text",
    },
    {
        id: "l8",
        language: "EN",
        level: "B1",
        title: "Sth else",
        author: '',
        grammaticalPoint:'',
        imageURL: `https://picsum.photos/id/18/300/300`,
        text: "There is no text",
    },
    {
        id: "l9",
        language: "EN",
        level: "B1",
        title: "Sth else",
        author: '',
        grammaticalPoint:'',
        imageURL: `https://picsum.photos/id/19/300/300`,
        text: "There is no text",
    },
    {
        id: "l10",
        language: "EN",
        level: "B1",
        title: "Sth else",
        author: '',
        grammaticalPoint:'',
        imageURL: `https://picsum.photos/id/32/300/300`,
        text: "There is no text",
    },
    {
        id: "l11",
        language: "EN",
        level: "B1",
        title: "Sth else",
        author: '',
        grammaticalPoint:'',
        imageURL: `https://picsum.photos/id/38/300/300`,
        text: "There is no text",
    },
    {
        id: "l12",
        language: "EN",
        level: "B1",
        title: "Sth else",
        author: '',
        grammaticalPoint:'',
        imageURL: `https://picsum.photos/id/412/300/300`,
        text: "There is no text",
    },
    {
        id: "l13",
        language: "DE",
        level: "B1",
        title: "ETWAS",
        author: '',
        grammaticalPoint:'',
        imageURL: `https://picsum.photos/id/412/300/300`,
        text: "There is no text",
    },

];

export default DUMMY_LESSONS;